### ISSUE TITLE
PodPoint Current Energy Sensor

### ISSUE THREAD

**Issue by Motormad48** [mattrayner/pod-point-home-assistant-component#44]
I have installed your PP HA component and everything seems to be working fine -  except...

The sensor.current_energy displays the current charge energy fine whilst the charger is plugged in.

However as soon as I unplug the charger is seems to create a significant negative value which then negates the previous data.

![IMG_0786](https://github.com/mattrayner/pod-point-home-assistant-component/assets/142654501/9ca6225d-c3da-4455-8f94-b173407e9381)

The attached shows three charging sessions and the huge negative spike. It doesn't seem to make any difference when I unplug - 1,2 or 3 hrs after charge complete it's all the same.
  
Any idea why this should be? Or what am I doing wrong?

Regards
David

**Comment by mattrayner** [comment]
Hi, I think this is down to how you are displaying the value, this seems to be showing a 'change' in value, assuming that any value will always be an increase.

In fact the sensor uses data provided by the PodPoint APIs to show the current charge session 's amount. This number resets to 0 when the session ends (usually when the cable is unplugged from either the pod, or vehicle).

When viewing the history data within Home Assistant directly it displays as intended:
<img width="1422" alt="image" src="https://github.com/mattrayner/pod-point-home-assistant-component/assets/3502902/d70a463f-ee1f-4369-86dc-08bfede5f398">

It looks like you are graphing the data in a different way in your tab which is the cause of your issue. Home assistant is saying  'the previous value was 2000w, now it's 0, so that's a -2000w change in value'. You might want to plot the change in 'Total Energy', as this is an always increasing value:

<img width="1407" alt="image" src="https://github.com/mattrayner/pod-point-home-assistant-component/assets/3502902/8391c115-66b0-4af7-bc7c-7263fac452ed">


I hope this helps!

**Comment by Motormad48** [comment]
Thanks Matt. Works perfectlyDaveSent from my iPhoneOn 4 Jan 2024, at 15:46, Matt Rayner ***@***.***> wrote:﻿
Closed #44 as completed.
